innoq/spacy

- assets/components/user-notifications/element.js
- assets/components/user-notifications/index.js
- assets/components/user-notifications/index.scss
- assets/components/waiting-queue/element.js
- assets/scripts/index.js
- assets/styles/_variables.scss
- assets/styles/index.scss
- resources/templates/event.html
- src/spacy/app.clj
With this commit I add a section to the UI for user notifications.
This section contains a List with the role=log attribute, which
means that when messages are added to the notifications, these will
be read out to a user who is using a screenreader.
This component listens to the same event as the waiting-queue element
(although I renamed it in session-suggested instead of
session-scheduled, since that seems more correct to me).
I also added a UI status element to the `Up Next` section. This element
has role=status, which means that when a session moves up in the line,
we need to modify this status. Then it will also be read out to a screen
reader -- I'm not sure if this is the best place for it, but I'm leaving
it there for now.
In the future, the Notifications may be a feature only for …
> Add component for user-notifications

- project.clj
- session.edn
- src/spacy/app.clj
- src/spacy/crux.clj
- src/spacy/data.clj
- src/spacy/domain.clj
- src/spacy/system.clj
This patch introduces https://opencrux.com/ as our data store. For now
all data are stored in an in-memory node that's destroyed when we stop
the system. Replacing it with a persistent solution should be a matter
of changing Crux configuration.
The Crux-related code lives in spacy.crux. That includes:
- a component that controls the lifecycle of a Crux node,
- logic for storing and retrieving events (i.e. our aggregates),
- subscription to Crux transactions, translating them into facts,
and sending to a provided core.async channel.
Every time we persist an event in a Crux node we store it as:
- a document with all facts removed, and
- all the new facts that we haven't stored yet.
Crux is responsible for keeping track of time. Each transaction has
:crux.db/valid-time. When we retrieve a …
> Put data in Crux

- Dockerfile
- src/spacy/main.clj
Not building an uberjar because:
- we're not compiling Clojure sources AOT, and
- this way we can reuse layers that contain Maven dependencies
and frontend bundles.
We can reuse most of the layers if only assets/* and src/* change.
> Add spacy.main and a Dockerfile

- .github/workflows/ci.yml
Save a bit of time by:
- caching Clojure dependencies between CI runs, and
- building the Docker image in parallel to running tests.
> CI touch-ups

- src/spacy/app.clj
- src/spacy/crux.clj
- src/spacy/data.clj
Events are identified by their URL slugs. Each event also gets
a :crux.db/id but it's an internal Crux detail. This patch should
make it more consistent.
Additionally, there's no need for a slug or an ID when persisting
an event. For now we're assuming the DB is seeded with an event that
has both a slug and an ID assigned beforehand.
> Use our vocabulary more consistently

- src/spacy/domain.clj
- test/spacy/domain_test.clj
This adds the function schedule-session to the domain which takes the
first element from the queue and places it in the schedule. I also
implemented the logic for determining if a session is actually able to
be positioned in the slot where we want to place (it needs to be the
first in the queue, the slot must be a valid one, and the slot must
not be already taken). I also added some unit tests with a test event
to test can-schedule-session? function. I'm not completely happy with
the tests: I feel like there is an opportunity here to use some generative
tests, which don't all use the same event data object. But writing the
unit a la TDD did help me to write the can-schedule-session? function with
all of its different conditions, so I figure that it is better than nothing.
> Adds schedule-session function to spacy.domain

- resources/templates/event.html
- src/spacy/app.clj
- src/spacy/domain.clj
This adds the schedule-session endpoint to the app.
I've pulled the
transformation of the current state into the domain namespace because
for the new available-slots property, I want to use the namespaced
keywords for the calculation (and we strip the namespaces from the keywords
before sending them to the UI).
I also renamed some variables which were called `session` to now be called
`event`, since we are referring to the current state of our event, not to
a specific session which has been suggested/scheduled.
After this change, I noticed some mistakes with the UI implementation
(the UI custom element always adds the new sessions to the queue, even
if the UpNext area is empty). But I will fix that in another MR.
This doesn't implement any UI behavior for session-scheduled yet:
When you …
> Adds endpoint for schedule-session and actions to trigger it in the UI

- src/spacy/app.clj
- src/spacy/domain.clj
Pulled the event->ui-representation into a event-view-model function
I agree that the event->ui-representation does not really belong in `domain`, so I moved it into a function here in `spacy.app`. I just made sure to add it before the keywords are dropped, so that we can still use the `domain/available-slots` function
> Pulled the event->ui-representation into a event-view-model function

- assets/components/session/index.js
- assets/components/session/index.scss
- assets/components/up-next/index.scss
- assets/components/waiting-queue/element.js
- assets/components/waiting-queue/index.scss
- assets/styles/_layout.scss
- assets/styles/_utilities.scss
- assets/styles/_variables.scss
- assets/styles/index.scss
- resources/templates/event.html
- resources/templates/index.html
- src/spacy/app.clj
One main thing: Now the session that is "up-next" is no longer separated
from the other entries in the Queue. It is listed directly in the ol list
in the queue, and the first entry now simply receives a special styling
with CSS.
This also adds a first CSS layout + very lightweight styling:
* make the sessions look like post-ITs (set a max-width, post-IT like colors, & box-shadow)
* basic CSS layout for the page
* add horizontal scrolling container around the table so that it doesn't
expand past the viewport on mobile devices
* very minimal styling for the header + nav links
I originally intended to use named CSS colors for the prototype, but they
just aren't very pretty. Instead, I've taken the colors from Tailwind CSS.
> Restructures HTML in view + adds very limited styling

- src/spacy/app.clj
- src/spacy/crux.clj
- src/spacy/data.clj
- src/spacy/domain.clj
- test/spacy/domain_test.clj
Events don't contain facts now. Domain functions that modify events return an _outcome_. Successful outcomes include the new state of the event and a collection of new facts. Both are persisted in Crux. Faulty outcomes come with an error code.
> Detach facts from events, add errors

- src/spacy/app.clj
- src/spacy/crux.clj
- src/spacy/system.clj
The term "event" is already present in our domain. FactsChannels don't
really roll off the tongue but should at least prevent any ambiguity.
> Rename spacy.system/Events to FactsChannels

- assets/components/fact-handler/element.js
- assets/components/session/index.js
- assets/components/user-notifications/element.js
- assets/components/waiting-queue/element.js
- resources/templates/event.html
- src/spacy/app.clj
The UI components now expect facts in exactly the format defined by our domain class. This means that I removed the `interpret-fact` function (we could always
add it in again later, if it proves necessary).
> Modifies the UI components to use the namespaced domain facts

- src/spacy/domain.clj
- test/spacy/domain_test.clj
This fixes a bug caused by adding sessions to a seq using conj.
It resulted in having them at the beginning of the waiting queue.
> Enqueue suggested sessions at the end

- assets/components/bulletin-board/element.js
- assets/components/bulletin-board/index.js
- assets/components/hijax-form/element.js
- assets/components/hijax-form/index.js
- assets/components/session/index.js
- assets/components/user-notifications/element.js
- assets/components/waiting-queue/element.js
- assets/scripts/index.js
- assets/styles/_layout.scss
- package-lock.json
- package.json
- resources/templates/event.html
- src/spacy/app.clj
The components to the following:
* bulletin-board (our session schedule) uses transclusion with the h-include
component to reload the whole contents of the schedule whenever the
session-scheduled event occurs: this is the simplest implementation, and I
did it this way because every cell needs to be updated to show the new
"Choose Slot" buttons for the new session which needs to be scheduled
* waiting-queue deletes the scheduled session from its list and thereby moves
the next session up in the queue
* user-notifications adds a notification to let screenreader users know which
session has been scheduled.
Additionally:
* I also switched the order of times and rooms in the table because for the
responsive behavior that I dream of in the future I would prefer to group
the data by time as …
> Listen and react to spacy.domain/session-scheduled event in the UI

- project.clj
- resources/config.edn
- src/spacy/config.clj
- src/spacy/crux.clj
- src/spacy/system.clj
Prior to this commit we stored Crux logs in memory. Now they're kept
in a database using JDBC. For the time being it's SQLite. I also tested
it locally with Postgres. A corresponding db-spec looks as follows:
{:dbtype "postgres"
:dbname "postgres"
:host "localhost"
:user "postgres"
:password "do not store passwords in git"}
See also https://opencrux.com/reference/jdbc.html
Once we end up switching to Postgres in production we might want to give
the following paragraph a careful read:
https://github.com/juxt/aero/blob/743e9bc495425b4a4a7c780f5e4b09f6680b4e7a/README.md#hide-passwords-in-local-private-files
I'm extending clojure.core/print-method for Crux to prevent printing
passwords when logging.
Related to #30
>    Store Crux logs in a relational database

- src/spacy/domain.clj
See it fail with this unexpected fact:
(s/explain ::facts [{::fact ::session-surprise
::sponsor "hi"
::session {::description "desc"
::title "title"
::id (java.util.UUID/randomUUID)}
::id (java.util.UUID/randomUUID)
::at (java.util.Date.)}])
Fixes #44
> Specify allowed ::fact values

- test/spacy/smoke_test.clj
Tests invoke Thread/sleep to give Crux time to index our transactions.
> Add a simple integration test

- assets/components/bulletin-board/element.js
- assets/styles/index.scss
- resources/templates/event/commands.html
- resources/templates/event/session.html
- resources/templates/move-session.html
- src/spacy/app.clj
- src/spacy/crux.clj
- src/spacy/domain.clj
- src/spacy/handler_util.clj
Closes #28 
This adds an HTML screen for `move-session` which renders the same bulletin-board as in the `event` template, but removing some elements (from that screen we don't want any actions ("delete", "move") to be shown, and we want to show some kind of placeholder in the screen where the current slot is actually positioned).
I also added an `(crux/await-tx ...)` wrapper within our `(persist! data event)` call, because the redirect was happening before the event had been persisted so the card did not move within the session schedule, and I added an optional `parameters` keyword argument to the `get-resource` function in `handler-util`.
> Move session

- assets/components/new-session/index.scss
- assets/components/up-next/element.js
- assets/components/user-notifications/element.js
- assets/components/user-notifications/index.scss
- assets/styles/_layout.scss
- resources/messages.edn
- resources/templates/event.html
- resources/templates/event/bulletin-board.html
- resources/templates/event/new-session.html
- resources/templates/event/up-next.html
- src/spacy/app.clj
- src/spacy/messages.clj
This refactors the user notification system (tested on screenreaders).
The hope is to find a system where user updates _that are actually useful_
are read out at the right time (only when something changed and we want
to inform the user about it).
I didn't really like the old usage of role=log, because the user only is
really interested in a status update once, and doesn't want to go back
and read old entries (this is an assumption. could be wrong about that).
So I've exchanged the role=log section for areas which are role=region
as well as aria-live=polite. I have (tried) to test this with a screenreader,
and it seems to work, but will need more testing in the future.
> Status refactoring

- session.edn
- src/spacy/app.clj
- src/spacy/crux.clj
- src/spacy/data.clj
- src/spacy/domain.clj
- test/spacy/domain_test.clj
This removes hardcoded events by adding event names to the model and fetching all event slugs from Crux.
> Remove hardcoded events

- resources/messages.edn
- resources/templates/event/new-session.html
- align order in german messages for "session-moved" with "session-scheduled"
- add commas and remove some grammatically misplaced 'n'
> fix some typos in german messages

- resources/templates/event/bulletin-board.html
- resources/templates/event/commands.html
- src/spacy/app.clj
This adds visually hidden text fields with Room & Time information
into the table schedule. (see #62)
Since this information is now in the DOM, I've also modified the
.session element and the `Choose Slot` actions to reference this
information via the `aria-describedby` attribute in the DOM.
I'm not completely sure yet if this is the best solution. I've tested
it myself, but we need to get a screenreader expert to test it if we
want to be sure that the UX is optimal.
> Working on adding visually hidden information to a table

- assets/components/fact-handler/element.js
- project.clj
- src/spacy/app.clj
- src/spacy/handler_util.clj
Attempt on #64 (need to test separately before closing the issue)
When you are running spacy behind a proxy, the proxy is likely to cut
off the connection if there is no activity after a specified period
of time (e.g. 1 minute). In a browser environment, this can also occur,
but the timeout is a lot longer (> 5 minutes).
In any case, we want to prevent our application from breaking the connection
off after such a short period of time, because it's possible that we could
have several longer breaks between presenting sessions.
In order to support this, I've built in a "keepalive" message which is sent
every 15 seconds and should keep the connection open (we will need to test
in a deployed environment if this really works).
I built it using the `chimes` library which generates periodic …
> Add keepalive event to the sse stream

- assets/components/bulletin-board/index.scss
- assets/components/session/index.scss
- assets/components/waiting-queue/index.scss
- assets/styles/_layout.scss
- resources/messages.edn
- resources/templates/event/bulletin-board.html
- resources/templates/event/session.html
- src/spacy/app.clj
Two changes:
Commit 1 (bdec38c) :
This restructures the `.session` component. The reason here is that the
way that the session title is currently formatted within the `<summary>`
elements causes empty strings to appear in the accessibility tree that
are labelled as being an "empty toggle" (#59)
This moves the sponsor out of the `<summary>` into a description list
underneath the `<details>` element and adds some styling to it.
Commit 2 (7506720):
This adds a `Schedule session` link to the session object itself which
is blended in when the session is at the top of the queue (I decided to
blend in the link as a progressive enhancement using CSS, because we
already have CSS rules which target the first element in the list).
This also adds some instructions for how to schedule a session that …
> Refactor schedule session

- assets/components/user-notifications/element.js
- resources/messages.edn
- resources/templates/event.html
Fixes #73
To fix this, I not only had to add the missing message to the markup,
but I also had to modify the user-notification custom element to have
a `notify-scheduled` option, because we only want the UI change to
trigger when a _scheduled_ session is deleted, not when a session is
deleted from the queue.
Because our facts still contain the `::room` and `::time` data when
the session was scheduled, I check for the existence of these
attributes to implement this option.
> Fix missing UI notification when a session is deleted

- src/spacy/app.clj
Fixes #71
This fixes a bug -- we actually want to delete the wrapping
:hijax-form and not the :form element inside of it. By
deleting the :form element, the <hijax-form> element throws
a JavaScript exception
> We want to remove the whole hijax-form when not logged in

- src/spacy/crux.clj
- src/spacy/data.clj
- src/spacy/handler_util.clj
Prior to this commit two concurrent writes often led to losing sessions.
Imagine the following scenario:
- request A reads an event in state S
- request B reads an event in state S
- request B adds a session to S and saves the event state Sb
- request A adds a session to S and saves the event state Sa
The client that sent B got a confirmation that their request was
successful. Alas, the event added by B is absent in Sa and lost.
This commit introduces a mechanism to make sure such race conditions do
not happen.
Upon saving the event state we use :crux.tx/match to make sure that no
concurrent writes occurred in the meantime. If there were no conflicts
the request is successful. Otherwise we retry the entire request after
a short wait.
If the request cannot be fulfilled after five retries, …
> Prevent losing sessions due to race conditions

- assets/components/slot-updater/element.js
When the queue is empty, the "spacy.ui/up-next" event is sent
with `{ detail: "spacy.ui/nobody-in-queue" }`. However, in the
`upNext` event of the `SlotUpdater` this was ignored and an
`appendAction` event was triggered. This fix now clears the
action when there is nobody in the queue.
> Fixes #81 - Clear the action in a slot when the queue is empty

- assets/components/waiting-queue/element.js
While using spacy during an event, one of the sessions that was
received to be placed in the queue appeared twice in the queue.
It is unclear as to why this occurred -- my assumption is that
the `::session-suggested` fact was for some reason sent twice
over the SSE Stream. It is also unclear to me why the session
would be sent twice (that's something we should look into),
but I also think it makes sense to modify the UI component
for the waiting-queue so that it is idempotent -- if the session
is sent twice to the UI, the second occurence will be ignored.
How to test this change:
Start the asset pipeline to make sure that the newest assets
are compiled:
```
npm start
```
in the Spacy repl:
```clojure
> (go)
> (require '[spacy.data :as data])
> (require '[spacy.domain :as domain])
> …
```
> Make adding session to queue idempotent

- project.clj
Updates all dependencies to the newest version.
This is perhaps all the more crucial because of a possible vulnerability with `logback` with a Version < 1.2.8 : https://logback.qos.ch/news.html (although this vulnerability seems less of an issue than the `log4j` debacle)
> Updating Dependencies
